version: "3.8"

services:
  backend:
    image: velesstan/backend:stage
    restart: always
    ports:
      - 3000:3000
  database:
    image: mongo:latest
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./mongodb:/data/db
    command: mongod --config /etc/mongod.conf
    env_file:
      - app.env
    ports:
      - "27017:27017"
